#pragma once

struct DisseminationField;
struct ReqUserLoginField;
struct RspUserLoginField;
struct UserLogoutField;
struct ForceUserLogoutField;
struct ReqAuthenticateField;
struct RspAuthenticateField;
struct AuthenticationInfoField;
struct RspUserLogin2Field;
struct TransferHeaderField;
struct TransferBankToFutureReqField;
struct TransferBankToFutureRspField;
struct TransferFutureToBankReqField;
struct TransferFutureToBankRspField;
struct TransferQryBankReqField;
struct TransferQryBankRspField;
struct TransferQryDetailReqField;
struct TransferQryDetailRspField;
struct RspInfoField;
struct ExchangeField;
struct ProductField;
struct InstrumentField;
struct BrokerField;
struct TraderField;
struct InvestorField;
struct TradingCodeField;
struct PartBrokerField;
struct SuperUserField;
struct SuperUserFunctionField;
struct InvestorGroupField;
struct TradingAccountField;
struct InvestorPositionField;
struct InstrumentMarginRateField;
struct InstrumentCommissionRateField;
struct DepthMarketDataField;
struct InstrumentTradingRightField;
struct BrokerUserField;
struct BrokerUserPasswordField;
struct BrokerUserFunctionField;
struct TraderOfferField;
struct SettlementInfoField;
struct InstrumentMarginRateAdjustField;
struct ExchangeMarginRateField;
struct ExchangeMarginRateAdjustField;
struct ExchangeRateField;
struct SettlementRefField;
struct CurrentTimeField;
struct CommPhaseField;
struct LoginInfoField;
struct LogoutAllField;
struct FrontStatusField;
struct UserPasswordUpdateField;
struct InputOrderField;
struct OrderField;
struct ExchangeOrderField;
struct ExchangeOrderInsertErrorField;
struct InputOrderActionField;
struct OrderActionField;
struct ExchangeOrderActionField;
struct ExchangeOrderActionErrorField;
struct ExchangeTradeField;
struct TradeField;
struct UserSessionField;
struct QryMaxOrderVolumeField;
struct SettlementInfoConfirmField;
struct SyncDepositField;
struct SyncFundMortgageField;
struct BrokerSyncField;
struct SyncingInvestorField;
struct SyncingTradingCodeField;
struct SyncingInvestorGroupField;
struct SyncingTradingAccountField;
struct SyncingInvestorPositionField;
struct SyncingInstrumentMarginRateField;
struct SyncingInstrumentCommissionRateField;
struct SyncingInstrumentTradingRightField;
struct QryOrderField;
struct QryTradeField;
struct QryInvestorPositionField;
struct QryTradingAccountField;
struct QryInvestorField;
struct QryTradingCodeField;
struct QryInvestorGroupField;
struct QryInstrumentMarginRateField;
struct QryInstrumentCommissionRateField;
struct QryInstrumentTradingRightField;
struct QryBrokerField;
struct QryTraderField;
struct QrySuperUserFunctionField;
struct QryUserSessionField;
struct QryPartBrokerField;
struct QryFrontStatusField;
struct QryExchangeOrderField;
struct QryOrderActionField;
struct QryExchangeOrderActionField;
struct QrySuperUserField;
struct QryExchangeField;
struct QryProductField;
struct QryInstrumentField;
struct QryDepthMarketDataField;
struct QryBrokerUserField;
struct QryBrokerUserFunctionField;
struct QryTraderOfferField;
struct QrySyncDepositField;
struct QrySettlementInfoField;
struct QryExchangeMarginRateField;
struct QryExchangeMarginRateAdjustField;
struct QryExchangeRateField;
struct QrySyncFundMortgageField;
struct QryHisOrderField;
struct OptionInstrMiniMarginField;
struct OptionInstrMarginAdjustField;
struct OptionInstrCommRateField;
struct OptionInstrTradeCostField;
struct QryOptionInstrTradeCostField;
struct QryOptionInstrCommRateField;
struct IndexPriceField;
struct InputExecOrderField;
struct InputExecOrderActionField;
struct ExecOrderField;
struct ExecOrderActionField;
struct QryExecOrderField;
struct ExchangeExecOrderField;
struct QryExchangeExecOrderField;
struct QryExecOrderActionField;
struct ExchangeExecOrderActionField;
struct QryExchangeExecOrderActionField;
struct ErrExecOrderField;
struct QryErrExecOrderField;
struct ErrExecOrderActionField;
struct QryErrExecOrderActionField;
struct OptionInstrTradingRightField;
struct QryOptionInstrTradingRightField;
struct InputForQuoteField;
struct ForQuoteField;
struct QryForQuoteField;
struct ExchangeForQuoteField;
struct QryExchangeForQuoteField;
struct InputQuoteField;
struct InputQuoteActionField;
struct QuoteField;
struct QuoteActionField;
struct QryQuoteField;
struct ExchangeQuoteField;
struct QryExchangeQuoteField;
struct QryQuoteActionField;
struct ExchangeQuoteActionField;
struct QryExchangeQuoteActionField;
struct OptionInstrDeltaField;
struct ForQuoteRspField;
struct StrikeOffsetField;
struct QryStrikeOffsetField;
struct InputBatchOrderActionField;
struct BatchOrderActionField;
struct ExchangeBatchOrderActionField;
struct QryBatchOrderActionField;
struct CombInstrumentGuardField;
struct QryCombInstrumentGuardField;
struct InputCombActionField;
struct CombActionField;
struct QryCombActionField;
struct ExchangeCombActionField;
struct QryExchangeCombActionField;
struct ProductExchRateField;
struct QryProductExchRateField;
struct QryForQuoteParamField;
struct ForQuoteParamField;
struct MMOptionInstrCommRateField;
struct QryMMOptionInstrCommRateField;
struct MMInstrumentCommissionRateField;
struct QryMMInstrumentCommissionRateField;
struct InstrumentOrderCommRateField;
struct QryInstrumentOrderCommRateField;
struct TradeParamField;
struct InstrumentMarginRateULField;
struct FutureLimitPosiParamField;
struct LoginForbiddenIPField;
struct IPListField;
struct InputOptionSelfCloseField;
struct InputOptionSelfCloseActionField;
struct OptionSelfCloseField;
struct OptionSelfCloseActionField;
struct QryOptionSelfCloseField;
struct ExchangeOptionSelfCloseField;
struct QryOptionSelfCloseActionField;
struct ExchangeOptionSelfCloseActionField;
struct SyncDelaySwapField;
struct QrySyncDelaySwapField;
struct InvestUnitField;
struct QryInvestUnitField;
struct SecAgentCheckModeField;
struct SecAgentTradeInfoField;
struct MarketDataField;
struct MarketDataBaseField;
struct MarketDataStaticField;
struct MarketDataLastMatchField;
struct MarketDataBestPriceField;
struct MarketDataBid23Field;
struct MarketDataAsk23Field;
struct MarketDataBid45Field;
struct MarketDataAsk45Field;
struct MarketDataUpdateTimeField;
struct MarketDataBandingPriceField;
struct MarketDataExchangeField;
struct SpecificInstrumentField;
struct InstrumentStatusField;
struct QryInstrumentStatusField;
struct InvestorAccountField;
struct PositionProfitAlgorithmField;
struct DiscountField;
struct QryTransferBankField;
struct TransferBankField;
struct QryInvestorPositionDetailField;
struct InvestorPositionDetailField;
struct TradingAccountPasswordField;
struct MDTraderOfferField;
struct QryMDTraderOfferField;
struct QryNoticeField;
struct NoticeField;
struct UserRightField;
struct QrySettlementInfoConfirmField;
struct LoadSettlementInfoField;
struct BrokerWithdrawAlgorithmField;
struct TradingAccountPasswordUpdateV1Field;
struct TradingAccountPasswordUpdateField;
struct QryCombinationLegField;
struct QrySyncStatusField;
struct CombinationLegField;
struct SyncStatusField;
struct QryLinkManField;
struct LinkManField;
struct QryBrokerUserEventField;
struct BrokerUserEventField;
struct QryContractBankField;
struct ContractBankField;
struct InvestorPositionCombineDetailField;
struct ParkedOrderField;
struct ParkedOrderActionField;
struct QryParkedOrderField;
struct QryParkedOrderActionField;
struct RemoveParkedOrderField;
struct RemoveParkedOrderActionField;
struct InvestorWithdrawAlgorithmField;
struct QryInvestorPositionCombineDetailField;
struct MarketDataAveragePriceField;
struct VerifyInvestorPasswordField;
struct UserIPField;
struct TradingNoticeInfoField;
struct TradingNoticeField;
struct QryTradingNoticeField;
struct QryErrOrderField;
struct ErrOrderField;
struct ErrorConditionalOrderField;
struct QryErrOrderActionField;
struct ErrOrderActionField;
struct QryExchangeSequenceField;
struct ExchangeSequenceField;
struct QryMaxOrderVolumeWithPriceField;
struct QryBrokerTradingParamsField;
struct BrokerTradingParamsField;
struct QryBrokerTradingAlgosField;
struct BrokerTradingAlgosField;
struct QueryBrokerDepositField;
struct BrokerDepositField;
struct QryCFMMCBrokerKeyField;
struct CFMMCBrokerKeyField;
struct CFMMCTradingAccountKeyField;
struct QryCFMMCTradingAccountKeyField;
struct BrokerUserOTPParamField;
struct ManualSyncBrokerUserOTPField;
struct CommRateModelField;
struct QryCommRateModelField;
struct MarginModelField;
struct QryMarginModelField;
struct EWarrantOffsetField;
struct QryEWarrantOffsetField;
struct QryInvestorProductGroupMarginField;
struct InvestorProductGroupMarginField;
struct QueryCFMMCTradingAccountTokenField;
struct CFMMCTradingAccountTokenField;
struct QryProductGroupField;
struct ProductGroupField;
struct BulletinField;
struct QryBulletinField;
struct MulticastInstrumentField;
struct QryMulticastInstrumentField;
struct AppIDAuthAssignField;
struct ReqOpenAccountField;
struct ReqCancelAccountField;
struct ReqChangeAccountField;
struct ReqTransferField;
struct RspTransferField;
struct ReqRepealField;
struct RspRepealField;
struct ReqQueryAccountField;
struct RspQueryAccountField;
struct FutureSignIOField;
struct RspFutureSignInField;
struct ReqFutureSignOutField;
struct RspFutureSignOutField;
struct ReqQueryTradeResultBySerialField;
struct RspQueryTradeResultBySerialField;
struct ReqDayEndFileReadyField;
struct ReturnResultField;
struct VerifyFuturePasswordField;
struct VerifyCustInfoField;
struct VerifyFuturePasswordAndCustInfoField;
struct DepositResultInformField;
struct ReqSyncKeyField;
struct RspSyncKeyField;
struct NotifyQueryAccountField;
struct TransferSerialField;
struct QryTransferSerialField;
struct NotifyFutureSignInField;
struct NotifyFutureSignOutField;
struct NotifySyncKeyField;
struct QryAccountregisterField;
struct AccountregisterField;
struct OpenAccountField;
struct CancelAccountField;
struct ChangeAccountField;
struct SecAgentACIDMapField;
struct QrySecAgentACIDMapField;
struct UserRightsAssignField;
struct BrokerUserRightAssignField;
struct DRTransferField;
struct FensUserInfoField;
struct CurrTransferIdentityField;
struct LoginForbiddenUserField;
struct QryLoginForbiddenUserField;
struct TradingAccountReserveField;
struct QryLoginForbiddenIPField;
struct QryIPListField;
struct QryUserRightsAssignField;
struct ReserveOpenAccountConfirmField;
struct ReserveOpenAccountField;
struct AccountPropertyField;
struct QryCurrDRIdentityField;
struct CurrDRIdentityField;
struct QrySecAgentCheckModeField;
struct QrySecAgentTradeInfoField;
struct ReqUserAuthMethodField;
struct RspUserAuthMethodField;
struct ReqGenUserCaptchaField;
struct RspGenUserCaptchaField;
struct ReqGenUserTextField;
struct RspGenUserTextField;
struct ReqUserLoginWithCaptchaField;
struct ReqUserLoginWithTextField;
struct ReqUserLoginWithOTPField;
struct ReqApiHandshakeField;
struct RspApiHandshakeField;
struct ReqVerifyApiKeyField;
struct DepartmentUserField;
struct QueryFreqField;
struct AuthForbiddenIPField;
struct QryAuthForbiddenIPField;
struct SyncDelaySwapFrozenField;
struct UserSystemInfoField;
struct AuthUserIDField;
struct AuthIPField;
struct QryClassifiedInstrumentField;
struct QryCombPromotionParamField;
struct CombPromotionParamField;
struct ReqUserLoginSMField;
struct QryRiskSettleInvstPositionField;
struct QryRiskSettleProductStatusField;
struct RiskSettleInvstPositionField;
struct RiskSettleProductStatusField;
struct SyncDeltaInfoField;
struct SyncDeltaProductStatusField;
struct SyncDeltaInvstPosDtlField;
struct SyncDeltaInvstPosCombDtlField;
struct SyncDeltaTradingAccountField;
struct SyncDeltaInitInvstMarginField;
struct SyncDeltaDceCombInstrumentField;
struct SyncDeltaInvstMarginRateField;
struct SyncDeltaExchMarginRateField;
struct SyncDeltaOptExchMarginField;
struct SyncDeltaOptInvstMarginField;
struct SyncDeltaInvstMarginRateULField;
struct SyncDeltaOptInvstCommRateField;
struct SyncDeltaInvstCommRateField;
struct SyncDeltaProductExchRateField;
struct SyncDeltaDepthMarketDataField;
struct SyncDeltaIndexPriceField;
struct SyncDeltaEWarrantOffsetField;
struct SPBMFutureParameterField;
struct SPBMOptionParameterField;
struct SPBMIntraParameterField;
struct SPBMInterParameterField;
struct SyncSPBMParameterEndField;
struct QrySPBMFutureParameterField;
struct QrySPBMOptionParameterField;
struct QrySPBMIntraParameterField;
struct QrySPBMInterParameterField;
struct SPBMPortfDefinitionField;
struct SPBMInvestorPortfDefField;
struct InvestorPortfMarginRatioField;
struct QrySPBMPortfDefinitionField;
struct QrySPBMInvestorPortfDefField;
struct QryInvestorPortfMarginRatioField;
struct InvestorProdSPBMDetailField;
struct QryInvestorProdSPBMDetailField;
struct PortfTradeParamSettingField;
struct InvestorTradingRightField;
struct MortgageParamField;
struct WithDrawParamField;
struct ThostUserFunctionField;
struct QryThostUserFunctionField;
struct SPBMAddOnInterParameterField;
struct QrySPBMAddOnInterParameterField;
struct QryInvestorCommoditySPMMMarginField;
struct QryInvestorCommodityGroupSPMMMarginField;
struct QrySPMMInstParamField;
struct QrySPMMProductParamField;
struct InvestorCommoditySPMMMarginField;
struct InvestorCommodityGroupSPMMMarginField;
struct SPMMInstParamField;
struct SPMMProductParamField;
struct QryTraderAssignField;
struct TraderAssignField;
struct InvestorInfoCntSettingField;
struct RCAMSCombProductInfoField;
struct RCAMSInstrParameterField;
struct RCAMSIntraParameterField;
struct RCAMSInterParameterField;
struct RCAMSShortOptAdjustParamField;
struct RCAMSInvestorCombPositionField;
struct InvestorProdRCAMSMarginField;
struct QryRCAMSCombProductInfoField;
struct QryRCAMSInstrParameterField;
struct QryRCAMSIntraParameterField;
struct QryRCAMSInterParameterField;
struct QryRCAMSShortOptAdjustParamField;
struct QryRCAMSInvestorCombPositionField;
struct QryInvestorProdRCAMSMarginField;
struct RULEInstrParameterField;
struct RULEIntraParameterField;
struct RULEInterParameterField;
struct QryRULEInstrParameterField;
struct QryRULEIntraParameterField;
struct QryRULEInterParameterField;
struct InvestorProdRULEMarginField;
struct QryInvestorProdRULEMarginField;
struct SyncDeltaSPBMPortfDefinitionField;
struct SyncDeltaSPBMInvstPortfDefField;
struct SyncDeltaSPBMFutureParameterField;
struct SyncDeltaSPBMOptionParameterField;
struct SyncDeltaSPBMIntraParameterField;
struct SyncDeltaSPBMInterParameterField;
struct SyncDeltaSPBMAddOnInterParamField;
struct SyncDeltaSPMMInstParamField;
struct SyncDeltaSPMMProductParamField;
struct SyncDeltaInvestorSPMMModelField;
struct SyncDeltaSPMMModelParamField;
struct SyncDeltaRCAMSCombProdInfoField;
struct SyncDeltaRCAMSInstrParameterField;
struct SyncDeltaRCAMSIntraParameterField;
struct SyncDeltaRCAMSInterParameterField;
struct SyncDeltaRCAMSSOptAdjParamField;
struct SyncDeltaRCAMSCombRuleDtlField;
struct SyncDeltaRCAMSInvstCombPosField;
struct SyncDeltaRULEInstrParameterField;
struct SyncDeltaRULEIntraParameterField;
struct SyncDeltaRULEInterParameterField;
struct IpAddrParamField;
struct QryIpAddrParamField;
struct TGIpAddrParamField;
struct QryTGIpAddrParamField;
struct TGSessionQryStatusField;
struct LocalAddrConfigField;
struct QryLocalAddrConfigField;
struct ReqQueryBankAccountBySecField;
struct RspQueryBankAccountBySecField;
struct ReqTransferBySecField;
struct RspTransferBySecField;
struct NotifyQueryFutureAccountBySecField;
struct ExitEmergencyField;
struct InvestorPortfMarginModelField;
struct InvestorPortfSettingField;
struct QryInvestorPortfSettingField;
struct UserPasswordUpdateFromSecField;
struct SettlementInfoConfirmFromSecField;
struct TradingAccountPasswordUpdateFromSecField;
struct RiskForbiddenRightField;
struct InvestorInfoCommRecField;
struct QryInvestorInfoCommRecField;
struct CombLegField;
struct QryCombLegField;
struct InputOffsetSettingField;
struct OffsetSettingField;
struct CancelOffsetSettingField;
struct QryOffsetSettingField;
struct AddrAppIDRelationField;
struct QryAddrAppIDRelationField;
struct FrontInfoField;

struct TraderApi;
struct TraderSpi;

#include "ctp4rs/src/lib.rs.h"
#include "ctp4rs/wrapper/include/CTraderSpi.h"
#include "ctp4rs/lib/6.7.9/ThostFtdcMdApi.h"
#include "ctp4rs/lib/6.7.9/ThostFtdcTraderApi.h"

#include "rust/cxx.h"
#include <memory>

struct TraderApi {
    TraderApi(const TraderSpi &gateway, rust::String flow_path);
    FrontInfoField GetFrontInfo() const;

    rust::String GetApiVersion() const;
    void Init() const;
    int32_t Join() const;
    rust::String GetTradingDay() const;
    void RegisterFront(rust::String pszFrontAddress) const;
    void RegisterNameServer(rust::String pszNsAddress) const;
    void RegisterFensUserInfo(FensUserInfoField pFensUserInfo) const;
    void SubscribePrivateTopic(int32_t nResumeType) const;
    void SubscribePublicTopic(int32_t nResumeType) const;
    int32_t ReqAuthenticate(ReqAuthenticateField pReqAuthenticateField, int32_t nRequestID) const;
    int32_t RegisterUserSystemInfo(UserSystemInfoField pUserSystemInfo) const;
    int32_t SubmitUserSystemInfo(UserSystemInfoField pUserSystemInfo) const;
    int32_t ReqUserLogin(ReqUserLoginField pReqUserLoginField, int32_t nRequestID) const;
    int32_t ReqUserLogout(UserLogoutField pUserLogout, int32_t nRequestID) const;
    int32_t ReqUserPasswordUpdate(UserPasswordUpdateField pUserPasswordUpdate, int32_t nRequestID) const;
    int32_t ReqTradingAccountPasswordUpdate(TradingAccountPasswordUpdateField pTradingAccountPasswordUpdate, int32_t nRequestID) const;
    int32_t ReqUserAuthMethod(ReqUserAuthMethodField pReqUserAuthMethod, int32_t nRequestID) const;
    int32_t ReqGenUserCaptcha(ReqGenUserCaptchaField pReqGenUserCaptcha, int32_t nRequestID) const;
    int32_t ReqGenUserText(ReqGenUserTextField pReqGenUserText, int32_t nRequestID) const;
    int32_t ReqUserLoginWithCaptcha(ReqUserLoginWithCaptchaField pReqUserLoginWithCaptcha, int32_t nRequestID) const;
    int32_t ReqUserLoginWithText(ReqUserLoginWithTextField pReqUserLoginWithText, int32_t nRequestID) const;
    int32_t ReqUserLoginWithOTP(ReqUserLoginWithOTPField pReqUserLoginWithOTP, int32_t nRequestID) const;
    int32_t ReqOrderInsert(InputOrderField pInputOrder, int32_t nRequestID) const;
    int32_t ReqParkedOrderInsert(ParkedOrderField pParkedOrder, int32_t nRequestID) const;
    int32_t ReqParkedOrderAction(ParkedOrderActionField pParkedOrderAction, int32_t nRequestID) const;
    int32_t ReqOrderAction(InputOrderActionField pInputOrderAction, int32_t nRequestID) const;
    int32_t ReqQryMaxOrderVolume(QryMaxOrderVolumeField pQryMaxOrderVolume, int32_t nRequestID) const;
    int32_t ReqSettlementInfoConfirm(SettlementInfoConfirmField pSettlementInfoConfirm, int32_t nRequestID) const;
    int32_t ReqRemoveParkedOrder(RemoveParkedOrderField pRemoveParkedOrder, int32_t nRequestID) const;
    int32_t ReqRemoveParkedOrderAction(RemoveParkedOrderActionField pRemoveParkedOrderAction, int32_t nRequestID) const;
    int32_t ReqExecOrderInsert(InputExecOrderField pInputExecOrder, int32_t nRequestID) const;
    int32_t ReqExecOrderAction(InputExecOrderActionField pInputExecOrderAction, int32_t nRequestID) const;
    int32_t ReqForQuoteInsert(InputForQuoteField pInputForQuote, int32_t nRequestID) const;
    int32_t ReqQuoteInsert(InputQuoteField pInputQuote, int32_t nRequestID) const;
    int32_t ReqQuoteAction(InputQuoteActionField pInputQuoteAction, int32_t nRequestID) const;
    int32_t ReqBatchOrderAction(InputBatchOrderActionField pInputBatchOrderAction, int32_t nRequestID) const;
    int32_t ReqOptionSelfCloseInsert(InputOptionSelfCloseField pInputOptionSelfClose, int32_t nRequestID) const;
    int32_t ReqOptionSelfCloseAction(InputOptionSelfCloseActionField pInputOptionSelfCloseAction, int32_t nRequestID) const;
    int32_t ReqCombActionInsert(InputCombActionField pInputCombAction, int32_t nRequestID) const;
    int32_t ReqQryOrder(QryOrderField pQryOrder, int32_t nRequestID) const;
    int32_t ReqQryTrade(QryTradeField pQryTrade, int32_t nRequestID) const;
    int32_t ReqQryInvestorPosition(QryInvestorPositionField pQryInvestorPosition, int32_t nRequestID) const;
    int32_t ReqQryTradingAccount(QryTradingAccountField pQryTradingAccount, int32_t nRequestID) const;
    int32_t ReqQryInvestor(QryInvestorField pQryInvestor, int32_t nRequestID) const;
    int32_t ReqQryTradingCode(QryTradingCodeField pQryTradingCode, int32_t nRequestID) const;
    int32_t ReqQryInstrumentMarginRate(QryInstrumentMarginRateField pQryInstrumentMarginRate, int32_t nRequestID) const;
    int32_t ReqQryInstrumentCommissionRate(QryInstrumentCommissionRateField pQryInstrumentCommissionRate, int32_t nRequestID) const;
    int32_t ReqQryExchange(QryExchangeField pQryExchange, int32_t nRequestID) const;
    int32_t ReqQryProduct(QryProductField pQryProduct, int32_t nRequestID) const;
    int32_t ReqQryInstrument(QryInstrumentField pQryInstrument, int32_t nRequestID) const;
    int32_t ReqQryDepthMarketData(QryDepthMarketDataField pQryDepthMarketData, int32_t nRequestID) const;
    int32_t ReqQryTraderOffer(QryTraderOfferField pQryTraderOffer, int32_t nRequestID) const;
    int32_t ReqQrySettlementInfo(QrySettlementInfoField pQrySettlementInfo, int32_t nRequestID) const;
    int32_t ReqQryTransferBank(QryTransferBankField pQryTransferBank, int32_t nRequestID) const;
    int32_t ReqQryInvestorPositionDetail(QryInvestorPositionDetailField pQryInvestorPositionDetail, int32_t nRequestID) const;
    int32_t ReqQryNotice(QryNoticeField pQryNotice, int32_t nRequestID) const;
    int32_t ReqQrySettlementInfoConfirm(QrySettlementInfoConfirmField pQrySettlementInfoConfirm, int32_t nRequestID) const;
    int32_t ReqQryInvestorPositionCombineDetail(QryInvestorPositionCombineDetailField pQryInvestorPositionCombineDetail, int32_t nRequestID) const;
    int32_t ReqQryCFMMCTradingAccountKey(QryCFMMCTradingAccountKeyField pQryCFMMCTradingAccountKey, int32_t nRequestID) const;
    int32_t ReqQryEWarrantOffset(QryEWarrantOffsetField pQryEWarrantOffset, int32_t nRequestID) const;
    int32_t ReqQryInvestorProductGroupMargin(QryInvestorProductGroupMarginField pQryInvestorProductGroupMargin, int32_t nRequestID) const;
    int32_t ReqQryExchangeMarginRate(QryExchangeMarginRateField pQryExchangeMarginRate, int32_t nRequestID) const;
    int32_t ReqQryExchangeMarginRateAdjust(QryExchangeMarginRateAdjustField pQryExchangeMarginRateAdjust, int32_t nRequestID) const;
    int32_t ReqQryExchangeRate(QryExchangeRateField pQryExchangeRate, int32_t nRequestID) const;
    int32_t ReqQrySecAgentACIDMap(QrySecAgentACIDMapField pQrySecAgentACIDMap, int32_t nRequestID) const;
    int32_t ReqQryProductExchRate(QryProductExchRateField pQryProductExchRate, int32_t nRequestID) const;
    int32_t ReqQryProductGroup(QryProductGroupField pQryProductGroup, int32_t nRequestID) const;
    int32_t ReqQryMMInstrumentCommissionRate(QryMMInstrumentCommissionRateField pQryMMInstrumentCommissionRate, int32_t nRequestID) const;
    int32_t ReqQryMMOptionInstrCommRate(QryMMOptionInstrCommRateField pQryMMOptionInstrCommRate, int32_t nRequestID) const;
    int32_t ReqQryInstrumentOrderCommRate(QryInstrumentOrderCommRateField pQryInstrumentOrderCommRate, int32_t nRequestID) const;
    int32_t ReqQrySecAgentTradingAccount(QryTradingAccountField pQryTradingAccount, int32_t nRequestID) const;
    int32_t ReqQrySecAgentCheckMode(QrySecAgentCheckModeField pQrySecAgentCheckMode, int32_t nRequestID) const;
    int32_t ReqQrySecAgentTradeInfo(QrySecAgentTradeInfoField pQrySecAgentTradeInfo, int32_t nRequestID) const;
    int32_t ReqQryOptionInstrTradeCost(QryOptionInstrTradeCostField pQryOptionInstrTradeCost, int32_t nRequestID) const;
    int32_t ReqQryOptionInstrCommRate(QryOptionInstrCommRateField pQryOptionInstrCommRate, int32_t nRequestID) const;
    int32_t ReqQryExecOrder(QryExecOrderField pQryExecOrder, int32_t nRequestID) const;
    int32_t ReqQryForQuote(QryForQuoteField pQryForQuote, int32_t nRequestID) const;
    int32_t ReqQryQuote(QryQuoteField pQryQuote, int32_t nRequestID) const;
    int32_t ReqQryOptionSelfClose(QryOptionSelfCloseField pQryOptionSelfClose, int32_t nRequestID) const;
    int32_t ReqQryInvestUnit(QryInvestUnitField pQryInvestUnit, int32_t nRequestID) const;
    int32_t ReqQryCombInstrumentGuard(QryCombInstrumentGuardField pQryCombInstrumentGuard, int32_t nRequestID) const;
    int32_t ReqQryCombAction(QryCombActionField pQryCombAction, int32_t nRequestID) const;
    int32_t ReqQryTransferSerial(QryTransferSerialField pQryTransferSerial, int32_t nRequestID) const;
    int32_t ReqQryAccountregister(QryAccountregisterField pQryAccountregister, int32_t nRequestID) const;
    int32_t ReqQryContractBank(QryContractBankField pQryContractBank, int32_t nRequestID) const;
    int32_t ReqQryParkedOrder(QryParkedOrderField pQryParkedOrder, int32_t nRequestID) const;
    int32_t ReqQryParkedOrderAction(QryParkedOrderActionField pQryParkedOrderAction, int32_t nRequestID) const;
    int32_t ReqQryTradingNotice(QryTradingNoticeField pQryTradingNotice, int32_t nRequestID) const;
    int32_t ReqQryBrokerTradingParams(QryBrokerTradingParamsField pQryBrokerTradingParams, int32_t nRequestID) const;
    int32_t ReqQryBrokerTradingAlgos(QryBrokerTradingAlgosField pQryBrokerTradingAlgos, int32_t nRequestID) const;
    int32_t ReqQueryCFMMCTradingAccountToken(QueryCFMMCTradingAccountTokenField pQueryCFMMCTradingAccountToken, int32_t nRequestID) const;
    int32_t ReqFromBankToFutureByFuture(ReqTransferField pReqTransfer, int32_t nRequestID) const;
    int32_t ReqFromFutureToBankByFuture(ReqTransferField pReqTransfer, int32_t nRequestID) const;
    int32_t ReqQueryBankAccountMoneyByFuture(ReqQueryAccountField pReqQueryAccount, int32_t nRequestID) const;
    int32_t ReqQryClassifiedInstrument(QryClassifiedInstrumentField pQryClassifiedInstrument, int32_t nRequestID) const;
    int32_t ReqQryCombPromotionParam(QryCombPromotionParamField pQryCombPromotionParam, int32_t nRequestID) const;
    int32_t ReqQryRiskSettleInvstPosition(QryRiskSettleInvstPositionField pQryRiskSettleInvstPosition, int32_t nRequestID) const;
    int32_t ReqQryRiskSettleProductStatus(QryRiskSettleProductStatusField pQryRiskSettleProductStatus, int32_t nRequestID) const;
    int32_t ReqQrySPBMFutureParameter(QrySPBMFutureParameterField pQrySPBMFutureParameter, int32_t nRequestID) const;
    int32_t ReqQrySPBMOptionParameter(QrySPBMOptionParameterField pQrySPBMOptionParameter, int32_t nRequestID) const;
    int32_t ReqQrySPBMIntraParameter(QrySPBMIntraParameterField pQrySPBMIntraParameter, int32_t nRequestID) const;
    int32_t ReqQrySPBMInterParameter(QrySPBMInterParameterField pQrySPBMInterParameter, int32_t nRequestID) const;
    int32_t ReqQrySPBMPortfDefinition(QrySPBMPortfDefinitionField pQrySPBMPortfDefinition, int32_t nRequestID) const;
    int32_t ReqQrySPBMInvestorPortfDef(QrySPBMInvestorPortfDefField pQrySPBMInvestorPortfDef, int32_t nRequestID) const;
    int32_t ReqQryInvestorPortfMarginRatio(QryInvestorPortfMarginRatioField pQryInvestorPortfMarginRatio, int32_t nRequestID) const;
    int32_t ReqQryInvestorProdSPBMDetail(QryInvestorProdSPBMDetailField pQryInvestorProdSPBMDetail, int32_t nRequestID) const;
    int32_t ReqQryInvestorCommoditySPMMMargin(QryInvestorCommoditySPMMMarginField pQryInvestorCommoditySPMMMargin, int32_t nRequestID) const;
    int32_t ReqQryInvestorCommodityGroupSPMMMargin(QryInvestorCommodityGroupSPMMMarginField pQryInvestorCommodityGroupSPMMMargin, int32_t nRequestID) const;
    int32_t ReqQrySPMMInstParam(QrySPMMInstParamField pQrySPMMInstParam, int32_t nRequestID) const;
    int32_t ReqQrySPMMProductParam(QrySPMMProductParamField pQrySPMMProductParam, int32_t nRequestID) const;
    int32_t ReqQrySPBMAddOnInterParameter(QrySPBMAddOnInterParameterField pQrySPBMAddOnInterParameter, int32_t nRequestID) const;
    int32_t ReqQryRCAMSCombProductInfo(QryRCAMSCombProductInfoField pQryRCAMSCombProductInfo, int32_t nRequestID) const;
    int32_t ReqQryRCAMSInstrParameter(QryRCAMSInstrParameterField pQryRCAMSInstrParameter, int32_t nRequestID) const;
    int32_t ReqQryRCAMSIntraParameter(QryRCAMSIntraParameterField pQryRCAMSIntraParameter, int32_t nRequestID) const;
    int32_t ReqQryRCAMSInterParameter(QryRCAMSInterParameterField pQryRCAMSInterParameter, int32_t nRequestID) const;
    int32_t ReqQryRCAMSShortOptAdjustParam(QryRCAMSShortOptAdjustParamField pQryRCAMSShortOptAdjustParam, int32_t nRequestID) const;
    int32_t ReqQryRCAMSInvestorCombPosition(QryRCAMSInvestorCombPositionField pQryRCAMSInvestorCombPosition, int32_t nRequestID) const;
    int32_t ReqQryInvestorProdRCAMSMargin(QryInvestorProdRCAMSMarginField pQryInvestorProdRCAMSMargin, int32_t nRequestID) const;
    int32_t ReqQryRULEInstrParameter(QryRULEInstrParameterField pQryRULEInstrParameter, int32_t nRequestID) const;
    int32_t ReqQryRULEIntraParameter(QryRULEIntraParameterField pQryRULEIntraParameter, int32_t nRequestID) const;
    int32_t ReqQryRULEInterParameter(QryRULEInterParameterField pQryRULEInterParameter, int32_t nRequestID) const;
    int32_t ReqQryInvestorProdRULEMargin(QryInvestorProdRULEMarginField pQryInvestorProdRULEMargin, int32_t nRequestID) const;
    int32_t ReqQryInvestorPortfSetting(QryInvestorPortfSettingField pQryInvestorPortfSetting, int32_t nRequestID) const;
    int32_t ReqQryInvestorInfoCommRec(QryInvestorInfoCommRecField pQryInvestorInfoCommRec, int32_t nRequestID) const;
    int32_t ReqQryCombLeg(QryCombLegField pQryCombLeg, int32_t nRequestID) const;
    int32_t ReqOffsetSetting(InputOffsetSettingField pInputOffsetSetting, int32_t nRequestID) const;
    int32_t ReqCancelOffsetSetting(InputOffsetSettingField pInputOffsetSetting, int32_t nRequestID) const;
    int32_t ReqQryOffsetSetting(QryOffsetSettingField pQryOffsetSetting, int32_t nRequestID) const;

    const TraderSpi &gateway;
    CThostFtdcTraderApi *api;
    CTraderSpi *spi;
};

std::unique_ptr<TraderApi> CreateTraderApi(const TraderSpi &gateway, rust::String flow_path);
